version: '3.8'
services:
  app:
    build: .
    volumes:
    - .:/app
    links:
    - database
    ports:
      - "80:3000"
    restart: on-failure
  database:
    image: mongo:4.4
    restart: always